version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
  producer:
    build: ./Producer
    container_name: Rproducer-app
    depends_on:
      - rabbitmq
  consumer:
    build: ./Consumer
    container_name: Rconsumer-app
    depends_on:
      - rabbitmq
